### ISSUE TITLE
Fix related gist (Step 6: Setting up Flask)

### ISSUE THREAD

**Issue by d2718nis** [dvf/blockchain#122]
What's wrong
------
@dvf it would be great if you could fix [Step 6: Setting up Flask](https://gist.github.com/dvf/0ccdfdfd4dadf0a53a82d7a1b2438c4e) gist, it affects the workflow at the [Learn Blockchains by Building One](https://hackernoon.com/learn-blockchains-by-building-one-117428612f46) article. Also there is no way to mention someone at the gist comments, so I created this issue instead.

Expected behavior
------
[full_chain](https://gist.github.com/dvf/0ccdfdfd4dadf0a53a82d7a1b2438c4e#file-blockchain-py-L33) endpoint should return JSON:
```
{
  "chain": [
    {
      "index": 1, 
      "previous_hash": 1, 
      "proof": 100, 
      "timestamp": 1532563934.4369285, 
      "transactions": []
    }
  ], 
  "length": 1
}
```

Actual behavior
-----
`NameError` raised while trying to access the `full_chain` endpoint: 
```
Traceback (most recent call last):
  File "~/blockchain/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__        
    return self.wsgi_app(environ, start_response)
  File "~/blockchain/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app        
    response = self.handle_exception(e)
  File "~/blockchain/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "~/blockchain/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise       
    raise value
  File "~/blockchain/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app        
    response = self.full_dispatch_request()
  File "~/blockchain/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "~/blockchain/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "~/blockchain/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise       
    raise value
  File "~/blockchain/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "~/blockchain/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "~/blockchain/blockchain.py", line 132, in full_chain                                        
    return jsonify(response), 200
NameError: name 'jsonify' is not defined
```

Solution
----
Fix imports [here](https://gist.github.com/dvf/0ccdfdfd4dadf0a53a82d7a1b2438c4e#file-blockchain-py-L7), replace
`from flask import Flask`
with
`from flask import Flask, jsonify`

**Comment by dvf** [comment]
Thanks for this!
