### ISSUE TITLE
TypeError: new_block() got an unexpected keyword argument 'previous_hash'

### ISSUE THREAD

**Issue by Cyberodd** [dvf/blockchain#145]
Getting this error  when I try to run my project, no idea how or why it occur and few solutions exist that even remotely resemble it.
Traceback:
(venv) C:\Users\Kanverse\PycharmProject\blockchain>python blockchain.py
Traceback (most recent call last):
  File "blockchain.py", line 146, in <module>
    blockchain = Blockchain()
  File "blockchain.py", line 18, in __init__
    self.new_block(previous_hash='1', proof=100)
TypeError: new_block() got an unexpected keyword argument 'previous_hash'

Any help would be greatly appreciated.

**Comment by Cyberodd** [comment]
`(venv) C:\Users\Kanverse\PycharmProject\blockchain>python blockchain.py
Traceback (most recent call last):
  File "blockchain.py", line 146, in <module>
    blockchain = Blockchain()
  File "blockchain.py", line 18, in __init__
    self.new_block(previous_hash='1', proof=100)
TypeError: new_block() got an unexpected keyword argument 'previous_hash'
`

**Comment by Cyberodd** [comment]
Files hadn't indexed in IDE
