### ISSUE TITLE
AttributeError when registering a node

### ISSUE THREAD

**Issue by davesie** [dvf/blockchain#45]
Hey,

All dependencies are installed: 

![image](https://user-images.githubusercontent.com/20534071/32912686-18b00842-cb10-11e7-9925-8306443533db.png)

If I run two nodes and I want to register one to the other, I get this error:
`AttributeError: 'NoneType' object has no attribute 'get'`
I use Postman and do a `POST` to `http://localhost:5000/nodes/register`
With this body:
```
{
	"nodes": ["http://127.0.0.1:5001"]	
}
```

I started the nodes like this:
```
$ pipenv run python blockchain.py
$ pipenv run python blockchain.py -p 5001
```
Same with adding new transactions.
`POST` to `http://localhost:5000/transactions/new` : 
```
{
    "sender": "d4ee26eee15148ee92c6cd394edd974e",
    "recipient": "ae348f5c97d14ec887b922699628e8c0",
    "amount": 1
}
```
Here the full error:
```
[2017-11-16 20:50:33,482] ERROR in app: Exception on /transactions/new [POST]
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/blockchain-ji30_lee/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "~/.local/share/virtualenvs/blockchain-ji30_lee/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "~/.local/share/virtualenvs/blockchain-ji30_lee/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "~/.local/share/virtualenvs/blockchain-ji30_lee/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "~/.local/share/virtualenvs/blockchain-ji30_lee/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "~/.local/share/virtualenvs/blockchain-ji30_lee/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "blockchain.py", line 221, in new_transaction
    if not all(k in values for k in required):
  File "blockchain.py", line 221, in <genexpr>
    if not all(k in values for k in required):
TypeError: argument of type 'NoneType' is not iterable
127.0.0.1 - - [16/Nov/2017 20:50:33] "POST /transactions/new HTTP/1.1" 500 -

```
What am I doing wrong?

**Comment by JimiPedros** [comment]
@davesie how did you fix this error? I cannot get 2 nodes operating on different ports to operate/sync on the same chain

**Comment by davesie** [comment]
Sorry that I just answer now. I think I fixed it by getting the latest version of the code.
Did you get it working by now?

**Comment by JimiPedros** [comment]
I did not get it working

**Comment by davesie** [comment]
@JimiPedros I had to set the Body in Postman to "JSON (application/json)". Did you do that? This solved it for me.
