### ISSUE TITLE
TypeError on Postman POST request

### ISSUE THREAD

**Issue by StrattonStudios** [dvf/blockchain#48]
Awesome project/blog.

Has anyone ran into the following error? First time Postman user so i have a hunch im not using the ui correctly...

Thanks in advance,
G

TypeError: argument of type 'NoneType' is not iterable
127.0.0.1 - - [23/Nov/2017 13:56:27] "POST /transactions/new HTTP/1.1" 500 -
[2017-11-23 13:57:17,723] ERROR in app: Exception on /transactions/new [POST]
Traceback (most recent call last):
  File "/Users/StrattonStudios/.pyenv/versions/qblockchain/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/StrattonStudios/.pyenv/versions/qblockchain/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/StrattonStudios/.pyenv/versions/qblockchain/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/StrattonStudios/.pyenv/versions/qblockchain/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/StrattonStudios/.pyenv/versions/qblockchain/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/StrattonStudios/.pyenv/versions/qblockchain/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "blockchain.py", line 215, in new_transaction
    if not all(k in values for k in required):
  File "blockchain.py", line 215, in <genexpr>
    if not all(k in values for k in required):
TypeError: argument of type 'NoneType' is not iterable

**Comment by StrattonStudios** [comment]
Function throwing error:

`def new_transaction():
    values = request.get_json()
    response = {
        'message': "Missing values",
    }

    # Check that the required fields are in the POST'ed data
    required = ['sender', 'recipient', 'amount']

    if not all(k in values for k in required):
        return jsonify(response), 400

    # Create a new Transaction
    index = blockchain.new_transaction(values['sender'], values['recipient'], values['amount'])

    response = {'message': f'Transaction will be added to Block {index}'}
    return jsonify(response), 201
`

**Comment by StrattonStudios** [comment]
Closed:

Postman: Headers > contenttype needs to be checked off.
