### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by bihdliulin** [dvf/blockchain#75]
I have following  error:
ERROR in app: Exception on /transactions/new [POST]
  File "C:/Users/小草/Downloads/Compressed/blockchain-master/blockchain-master/blockchain.py", line 237, in new_transaction
    if not all(k in values for k in required):
 File "C:/Users/小草/Downloads/Compressed/blockchain-master/blockchain-master/blockchain.py", line 237, in <genexpr>
    if not all(k in values for k in required):
TypeError: argument of type 'NoneType' is not iterable

**Comment by deion1130** [comment]
I made the following changes and the issue is solved. Please see below. I got the same error you did when I ran the program.  I believe it was caused by the get_json function not recognizing your transaction input format.

@app.route('/transactions/new', methods = ['POST'])
def new_transaction():
    values = request.get_json(force=True)
    required = ['sender', 'recipient', 'amount']
    if not all(k in values for k in required):
        return 'Missing Values', 400

**Comment by bihdliulin** [comment]
@deion1130 Thank you very much! I tried your suggestion. It works good.But another question troubles me:

1. when I debug this program with pycharm,following question appears:

Traceback (most recent call last):
  File "C:/Users/小草/PycharmProjects/untitled/block.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

2. when I debug this program with command line, it works good.

 Can you give me some suggestions?
Thank you!

**Comment by nadaj** [comment]
Probably because in your PyCharm settings for the used project interpreter the package requests isn't installed. You should add it by going to Settings>Project:project_name>Project Interpreter. Click on the green plus, type 'requests' and install it.

**Comment by F0lamie** [comment]
I have the same issues :/
Adding args force=true for get_json functions dosen't help me at all.

DId you found the solution ?

**Comment by donburi** [comment]
@F0lamie - The solution above just yielded more problems for me. I finally fixed the issue when I specified in my API call that `"Content-Type": "application/json"`in the Header.

![screen shot 2018-09-16 at 13 10 46](https://user-images.githubusercontent.com/4899610/45598977-fa085480-b9b1-11e8-8952-0288c735e1c8.png)

**Comment by darmut** [comment]
> @F0lamie - The solution above just yielded more problems for me. I finally fixed the issue when I specified in my API call that `"Content-Type": "application/json"`in the Header.
> 
> ![screen shot 2018-09-16 at 13 10 46](https://user-images.githubusercontent.com/4899610/45598977-fa085480-b9b1-11e8-8952-0288c735e1c8.png)

This worked for me aswell.

**Comment by karolymisbah** [comment]
And it is all. Man is an animal animal is man is an
