### ISSUE TITLE
pip install pipenv IOError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by linuxhsj** [dvf/blockchain#79]
I installed pyhton 3.6.4.But when I exec the cmd  `pip install pipenv `,I got some Exception.
`Exception:
Traceback (most recent call last):
  File "/home/linux/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/linux/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/linux/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/linux/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/linux/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/linux/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/linux/.local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pathlib.pyc'
`
could you help me?Thanks in advance
My OS is ubuntukylin-16.04-desktop-amd64（Linux version 4.4.0-21-generic）

**Comment by linuxhsj** [comment]
@dvf @2gotgrossman @rbalazs @rbalazs @jwbixby @yuribol could you help me?Thanks in advance

**Comment by dvf** [comment]
This looks like a permission error with your local installation of Python. Have you tried reinstalling Python?

**Comment by srivkrnt** [comment]
Try running the pip command with sudo 

$ sudo pip install pipenv
